#ifndef WAR_OF_AGES_GAME_CONSTANTS_H
#define WAR_OF_AGES_GAME_CONSTANTS_H

const int NUM_OF_AGES = 4;
const int UNITS_PER_AGE = 3;
const int MAX_CANNON_SLOTS = 3;
const int UNITS_QUEUE_SIZE = 5;

const int INITIAL_MONEY = 200;

#endif  // WAR_OF_AGES_GAME_CONSTANTS_H
