#ifndef WAR_OF_AGES_GAME_OBJECT_SIZE_CONSTANTS_H
#define WAR_OF_AGES_GAME_OBJECT_SIZE_CONSTANTS_H

namespace war_of_ages {

const int BACKGROUND_WIDTH = 1920;
const int BACKGROUND_HEIGHT = 1080;

const int ROAD_WIDTH = 2500;
const int ROAD_HEIGHT = 500;

const int TOWER_WIDTH = 1920;
const int TOWER_HEIGHT = 1920;

const int CANNON_SLOT_WIDTH = 300;
const int CANNON_SLOT_HEIGHT = 300;

const int CANNON_WIDTH = 300;
const int CANNON_HEIGHT = 300;

//const int BACKGROUND_WIDTH = 1920;


}

#endif  // WAR_OF_AGES_GAME_OBJECT_SIZE_CONSTANTS_H
